name: Build Android APK with EAS

on:
  workflow_dispatch:
    inputs:
      build_profile:
        description: 'Build profile to use'
        required: true
        default: 'preview'
        type: choice
        options:
        - preview
        - production

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
      
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
      
    - name: Install EAS CLI
      run: npm install -g @expo/eas-cli
      
    - name: Build with EAS
      run: eas build --platform android --profile ${{ github.event.inputs.build_profile }} --non-interactive
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        
    - name: Get build URL
      run: |
        echo "Build completed! Check the EAS dashboard for download link."
        echo "Or run: eas build:list --platform=android --limit=1"
